version: 2
builds:
- id: ccv
  binary: ccv
  main: ./cmd/ccv
  ldflags:
  - >
    -s -w
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

changelog:
  use: github-native

release:
  extra_files:
  - glob: "{{ .Env.GITHUB_SBOM_PATH }}"
    name_template: "{{ .ProjectName }}.v{{ .Version }}.sbom.spdx.json"
